/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-04-23 07:57:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\th1,h1+form{\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t}\r\n");
      out.write("\th1,h1+form,form button{\r\n");
      out.write("\t\tmargin: 20px auto;\r\n");
      out.write("\t}\r\n");
      out.write("\tform label{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tbackground-color: gray; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1>입력페이지</h1>\r\n");
      out.write("\t\t<form action=\"insert.jsp\" onsubmit=\"return inputCheck();\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"name\">이름</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"name\" id=\"name\"/><span class=\"err\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"pay\">금액</label>\r\n");
      out.write("\t\t\t<input type=\"text\" min=\"0\" value=\"0\" name=\"pay\" id=\"pay\"/><span class=\"err\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"submit\">입력</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tvar nullErr=document.createTextNode('값이 비었음');\r\n");
      out.write("\tvar arrErr=document.getElementsByClassName('err');\r\n");
      out.write("\t\r\n");
      out.write("\tfunction inputCheck(){\r\n");
      out.write("\t\t\r\n");
      out.write("\tfor(var i=0;i<arrErr.length;i++){\r\n");
      out.write("\t\tif(arrErr[i].childNodes.length!=0){\r\n");
      out.write("\t\t\tarrErr[i].removeChild(nullErr);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\tvar arr=document.getElementsByTagName('input');\r\n");
      out.write("\t\tfor(var i=0;i<arr.length;i++){\r\n");
      out.write("\t\t\tconsole.log(arr[i].value);\r\n");
      out.write("\t\t\tif(arr[i].value.length==0){\r\n");
      out.write("\t\t\t\t//console.log(\"값이 비었음\");\r\n");
      out.write("\t\t\t\tarrErr[i].appendChild(nullErr);\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
