/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-04-23 01:35:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tul>li{\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\tul>li>span{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\tul>li>span:nth-child(1){\r\n");
      out.write("\t\twidth: 80px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul>li>span:nth-child(2){\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul>li>span:nth-child(3){\r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul>li>span:nth-child(4){\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\th1+div>a{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tbackground-color: red;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tborder-radius: 25px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tline-height: 50px;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tmargin-left: 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\th1+div>a:hover{\r\n");
      out.write("\t\tcolor:yellow;\r\n");
      out.write("\t\tline-height: 52px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>리스트페이지</h1>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>사번</span>\r\n");
      out.write("\t\t\t\t<span>이름</span>\r\n");
      out.write("\t\t\t\t<span>날짜</span>\r\n");
      out.write("\t\t\t\t<span>금액</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t");

			Class.forName("oracle.jdbc.driver.OracleDriver");
			String url="jdbc:oracle:thin:@localhost:1521:xe";
			String user="scott";
			String password="tiger";
			String sql="select * from guest02 order by sabun";
			Connection conn=null;
			try{
				conn=DriverManager.getConnection(url,user,password);
				PreparedStatement pstmt=conn.prepareStatement(sql);
				ResultSet rs=pstmt.executeQuery();
				while(rs.next()){
			
      out.write("\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>");
      out.print(rs.getInt("sabun") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span>");
      out.print(rs.getString("name") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span>");
      out.print(rs.getDate("nalja") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span>");
      out.print(rs.getInt("pay") );
      out.write("</span>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t");

				}
			}finally{
				conn.close();
			}
			
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<a href=\"add.jsp\">입력</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
