--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EX16 (
		NUM NUMBER(22 , 0)
	);

CREATE TABLE EX13 (
		NUM NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(9)
	);

CREATE TABLE EMP (
		EMPNO NUMBER(4 , 0) NOT NULL,
		ENAME VARCHAR2(10),
		JOB VARCHAR2(9),
		MGR NUMBER(4 , 0),
		HIREDATE DATE,
		SAL NUMBER(7 , 2),
		COMM NUMBER(7 , 2),
		DEPTNO NUMBER(2 , 0)
	);

CREATE TABLE EX12 (
		SU2 NUMBER(22 , 0),
		NUM NUMBER(22 , 0)
	);

CREATE TABLE EX03 (
		NUM NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(30) NOT NULL
	);

CREATE TABLE EX02 (
		NUM NUMBER(22 , 0),
		NAME VARCHAR2(30)
	);

CREATE TABLE EX10 (
		NUM NUMBER(22 , 0),
		GENDER VARCHAR2(3),
		NALJA DATE DEFAULT sysdate

	);

CREATE TABLE SALGRADE (
		GRADE NUMBER(22 , 0),
		LOSAL NUMBER(22 , 0),
		HISAL NUMBER(22 , 0)
	);

CREATE TABLE STUDENT (
		NUM NUMBER(22 , 0),
		NAME VARCHAR2(12),
		KOR NUMBER(3 , 0),
		ENG NUMBER(3 , 0),
		MATH NUMBER(3 , 0)
	);

CREATE TABLE DEPT (
		DEPTNO NUMBER(2 , 0) NOT NULL,
		DNAME VARCHAR2(14),
		LOC VARCHAR2(13)
	);

CREATE TABLE EX04 (
		NUM NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(9) NOT NULL
	);

CREATE TABLE EX09 (
		SABUN NUMBER(22 , 0) NOT NULL,
		NAME VARCHAR2(9) NOT NULL,
		NUM NUMBER(22 , 0)
	);

CREATE TABLE EX07 (
		NUM1 NUMBER(22 , 0) NOT NULL,
		NUM2 NUMBER(22 , 0),
		NUM3 NUMBER(22 , 0)
	);

CREATE TABLE EX11 (
		SU1 NUMBER(22 , 0),
		NUM NUMBER(22 , 0)
	);

CREATE TABLE EX08 (
		NUM NUMBER(22 , 0) NOT NULL,
		LOC VARCHAR2(6),
		TEL VARCHAR2(13)
	);

CREATE TABLE BONUS (
		ENAME VARCHAR2(10),
		JOB VARCHAR2(9),
		SAL NUMBER(22 , 0),
		COMM NUMBER(22 , 0)
	);

CREATE TABLE EX01 (
		NUM NUMBER(22 , 0),
		TXT VARCHAR2(5)
	);

CREATE TABLE COPYDEPT5 (
		DEPTNO NUMBER(2 , 0),
		DNAME VARCHAR2(14),
		LOC VARCHAR2(13)
	);

CREATE VIEW VIEW_DEPT (DEPTNO, DNAME, LOC) 
WITH CASCADED CHECK OPTION;

CREATE VIEW VIEW_DEPT2 (DEPTNO, DNAME, LOC) 
WITH CASCADED CHECK OPTION;

CREATE UNIQUE INDEX PK_DEPT ON DEPT (DEPTNO ASC);

CREATE UNIQUE INDEX SYS_C004023 ON EX09 (SABUN ASC);

CREATE UNIQUE INDEX SYS_C004015 ON EX04 (NAME ASC);

CREATE UNIQUE INDEX SYS_C004000 ON EX02 (NUM ASC);

CREATE UNIQUE INDEX SYS_C004008 ON EX03 (NUM ASC);

CREATE UNIQUE INDEX PK_EMP ON EMP (EMPNO ASC);

CREATE UNIQUE INDEX SYS_C004009 ON EX03 (NAME ASC);

CREATE UNIQUE INDEX SYS_C004001 ON EX02 (NAME ASC);

CREATE UNIQUE INDEX SYS_C004021 ON EX08 (NUM ASC);

CREATE UNIQUE INDEX SYS_C004012 ON EX07 (NUM1 ASC);

CREATE UNIQUE INDEX SYS_C004026 ON EX13 (NUM ASC);

CREATE UNIQUE INDEX SYS_C004016 ON EX04 (NUM ASC);

ALTER TABLE EX13 ADD CONSTRAINT SYS_C004026 PRIMARY KEY (NUM);

ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (EMPNO);

ALTER TABLE EX07 ADD CONSTRAINT SYS_C004012 PRIMARY KEY (NUM1);

ALTER TABLE EX04 ADD CONSTRAINT SYS_C004016 PRIMARY KEY (NUM);

ALTER TABLE DEPT ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO);

ALTER TABLE EX09 ADD CONSTRAINT SYS_C004023 PRIMARY KEY (SABUN);

ALTER TABLE EX08 ADD CONSTRAINT SYS_C004021 PRIMARY KEY (NUM);

ALTER TABLE EX09 ADD CONSTRAINT EX09_NUM_FK FOREIGN KEY (NUM)
	REFERENCES EX08 (NUM)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EMP ADD CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO)
	REFERENCES DEPT (DEPTNO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

