/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-06-25 11:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.3.1.slim.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    /*  header  */\r\n");
      out.write("    .main_font{\r\n");
      out.write("        font-family: 'Open Sans',sans-serif;\r\n");
      out.write("        color: #313131;\r\n");
      out.write("        line-height: 18px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: 800;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        text-shadow: none;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("    .header{\r\n");
      out.write("        padding: 36px 0 21px 0;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        border-top: 5px #d00b01 solid;\r\n");
      out.write("    }\r\n");
      out.write("    .nav>li{\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    .main_menu{\r\n");
      out.write("    }\r\n");
      out.write("    .menu_img{\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    .menu_login{\r\n");
      out.write("        float: right;\r\n");
      out.write("        margin-right: 18px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-control{\r\n");
      out.write("        height: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    .input_box{\r\n");
      out.write("    }\r\n");
      out.write("    .btn{\r\n");
      out.write("        padding: 4px 12px;\r\n");
      out.write("    }\r\n");
      out.write("    .menu_bar{\r\n");
      out.write("        width: 576px;\r\n");
      out.write("        float: right;\r\n");
      out.write("        padding-left: 13px;\r\n");
      out.write("    }\r\n");
      out.write("    .sub-menu{\r\n");
      out.write("        width: 113px;\r\n");
      out.write("        zoom: 1;\r\n");
      out.write("        margin-top: 22px;\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border-top: 4px #d00b01 solid;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .top-menu:hover .sub-menu{\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("    .nav>li{\r\n");
      out.write("        margin: 0px 3px;\r\n");
      out.write("    }\r\n");
      out.write("    .nav>li:visited ,.nav>li:active,.nav>li>a:visited,.nav>li>a:active{\r\n");
      out.write("        background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .nav>li>a{\r\n");
      out.write("        font-family: 'Open Sans',sans-serif;\r\n");
      out.write("        color: #313131;\r\n");
      out.write("        line-height: 18px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: 800;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        text-shadow: none;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("    .nav>li>a:hover{\r\n");
      out.write("        color: #c5c5c5;\r\n");
      out.write("        background: none;\r\n");
      out.write("    }\r\n");
      out.write("    /*  //header  */\r\n");
      out.write("\r\n");
      out.write("    /* main contents */\r\n");
      out.write("    .page_container{\r\n");
      out.write("        height: 500px;\r\n");
      out.write("        background-color: thistle;\r\n");
      out.write("    }\r\n");
      out.write("    /* //main contents  */\r\n");
      out.write("\r\n");
      out.write("    /* footer */\r\n");
      out.write("    .footer{\r\n");
      out.write("        background-color: #1e1e1e;\r\n");
      out.write("        padding: 23px 0px 26px 0px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer_L{\r\n");
      out.write("        width: 380px;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    .copyright{\r\n");
      out.write("        color: #444;\r\n");
      out.write("        line-height: 16px;\r\n");
      out.write("        font-family: Arial;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer_R{\r\n");
      out.write("        width: 563px;\r\n");
      out.write("        float: right;\r\n");
      out.write("        margin: 16px 0px 0px 0px;\r\n");
      out.write("    }\r\n");
      out.write("    .fright{\r\n");
      out.write("        float: right;\r\n");
      out.write("        margin-right: 18px;\r\n");
      out.write("    }\r\n");
      out.write("    .inp_search{\r\n");
      out.write("        height: 23px;\r\n");
      out.write("        color: #1e1e1e;\r\n");
      out.write("        background-color: #393939;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        border: 1px #393939 solid;\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer_menu{\r\n");
      out.write("        float: right;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    /* //footer */\r\n");
      out.write("@media all and (max-width: 991px) {\r\n");
      out.write("    /* header */\r\n");
      out.write("    .main_menu{\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .menu_img{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin: 0px 0px 10px 0px;\r\n");
      out.write("    }\r\n");
      out.write("    .menu_login{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin: 0px auto;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .menu_bar{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding-left: 76px;\r\n");
      out.write("    }\r\n");
      out.write("    /* //header */\r\n");
      out.write("    /* footer */\r\n");
      out.write("    .footer_L{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .footer_R{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    .fright{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .footer_menu{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding-left: 98px;\r\n");
      out.write("    }\r\n");
      out.write("    /* //footer */\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--header-->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("    \t<div class=\"wrap\">\r\n");
      out.write("            <nav class=\"main_menu container\">\r\n");
      out.write("                <div class=\"menu_img\">\r\n");
      out.write("                    <img src=\"img/c32fe01ca96fce6014427edc4656fe1d.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"menu_login\">\r\n");
      out.write("                    <form class=\"form-inline\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"sr-only\" for=\"exampleInputEmail3\">id</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control input_box\" placeholder=\"Enter ID\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"sr-only\" for=\"exampleInputPassword3\">password</label>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control input_box\" placeholder=\"Password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn send_btn\"><span class=\"main_font\">로그인</span></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"menu_bar\">\r\n");
      out.write("                    <ul class=\"nav\">\r\n");
      out.write("                      <li class=\"current\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                      <li><a href=\"about.html\">About</a></li>\r\n");
      out.write("                      <li class=\"top-menu\"><a href=\"javascript:{}\">Features</a>\r\n");
      out.write("                          <ul class=\"sub-menu\">\r\n");
      out.write("                              <li><a href=\"scaffolding.html\">Scaffolding</a></li>\r\n");
      out.write("                              <li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("                              <li><a href=\"shortcodes.html\">Shortcodes</a></li>\r\n");
      out.write("                              <li><a href=\"tables.html\">Tables</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"top-menu\"><a href=\"javascript:{}\">Portfolio</a>\r\n");
      out.write("                           <ul class=\"sub-menu\">\r\n");
      out.write("                              <li><a href=\"portfolio_2columns.html\">2 Columns</a></li>\r\n");
      out.write("                              <li><a href=\"portfolio_3columns.html\">3 Columns</a></li>\r\n");
      out.write("                              <li><a href=\"portfolio_4columns.html\">4 Columns</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>                                  \r\n");
      out.write("                      <li class=\"top-menu\"><a href=\"javascript:{}\">Blog</a>\r\n");
      out.write("                           <ul class=\"sub-menu\">\r\n");
      out.write("                              <li><a href=\"blog.html\">Blog with right sidebar</a></li>\r\n");
      out.write("                              <li><a href=\"blog_post.html\">Blog post</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><a href=\"contacts.html\">Contacts</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("             </nav>                \r\n");
      out.write("             \r\n");
      out.write("        </div>    \r\n");
      out.write("    </div>\r\n");
      out.write("    <!--//header-->    \r\n");
      out.write("     \r\n");
      out.write("    <!-- main contents -->\r\n");
      out.write("    <div class=\"page_container\">\r\n");
      out.write("        <!--slider-->\r\n");
      out.write("        <div id=\"main_slider\">\r\n");
      out.write("            <div class=\"camera_wrap\" id=\"camera_wrap_1\">\r\n");
      out.write("                <div data-src=\"img/slider/1.jpg\"></div>\r\n");
      out.write("                <div data-src=\"img/slider/2.jpg\"></div>\r\n");
      out.write("                <div data-src=\"img/slider/3.jpg\"></div>                                        \r\n");
      out.write("            </div><!-- #camera_wrap_1 -->\r\n");
      out.write("            <div class=\"clear\"></div>\t\r\n");
      out.write("        </div>        \r\n");
      out.write("        <!--//slider-->\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //main contents -->\r\n");
      out.write("\r\n");
      out.write("    <!--footer-->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"wrap\">\r\n");
      out.write("            \t<div class=\"container\">\r\n");
      out.write("                \t<div class=\"row\">\r\n");
      out.write("                \t\t<div class=\"footer_L\">\r\n");
      out.write("                        \t<div class=\"foot_logo\"><a href=\"index.html\"><img src=\"img/footer_logo.png\" alt=\"\" /></a></div>\r\n");
      out.write("                        \t<div class=\"copyright\">&copy; 2020 Jessica White. Professional Fashion Photography. All Rights Reserved.</div>                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"footer_R\">\r\n");
      out.write("                            <div class=\"fright\">\r\n");
      out.write("                                <form action=\"#\" method=\"post\">\r\n");
      out.write("                                    <input class=\"inp_search\" name=\"name\" type=\"text\" value=\"   Search the Site\" onfocus=\"if (this.value == 'Search the Site') this.value = '';\" onblur=\"if (this.value == '') this.value = 'Search the Site';\" />\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"footer_menu\">\r\n");
      out.write("                                <ul class=\"nav\">\r\n");
      out.write("                                    <li><a href=\"index.html\" class=\"current\">Home</a></li>\r\n");
      out.write("                                    <li><a href=\"about.html\">About</a></li>\r\n");
      out.write("                                    <li><a href=\"scaffolding.html\">features</a></li>\r\n");
      out.write("                                    <li><a href=\"portfolio_2columns.html\">Portfolio</a></li>\r\n");
      out.write("                                    <li><a href=\"blog.html\">Blog</a></li>\r\n");
      out.write("                                    <li><a href=\"contacts.html\">Contacts</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--//footer-->    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
